/// @file Strategy.h
/// @brief Strategy concept and order submission types.
///
/// A Strategy is user-written code that reacts to book updates and trade
/// events, producing simulated orders (SimOrder). The concept is enforced
/// at compile time — no virtual dispatch, no runtime overhead.
///
/// ## How to write a strategy
///
/// 1. Define a struct/class with the required member functions.
/// 2. Use `OrderSubmitter` to send orders to the simulation layer.
/// 3. Pass your strategy type as a template argument to Engine.
///
/// @code
/// struct MyStrategy {
///     void on_book_update(SymbolId sym, const LOB& book,
///                         const Event& event, OrderSubmitter& submitter) {
///         if (book.best_bid() > 0 && book.best_ask() < 1e9) {
///             submitter.submit({...});
///         }
///     }
///     void on_fill(const Fill& fill) {
///         // Track position, update state...
///     }
/// };
/// static_assert(Strategy<MyStrategy>);
/// @endcode

#pragma once
#include "lobe/Book/LOB.h"
#include "lobe/Feed/Event.h"
#include <concepts>
#include <cstdint>
#include <vector>

namespace lobe {

// ============================================================
// Simulated order types
// ============================================================

/// @brief Types of simulated orders a strategy can submit.
enum class SimOrderType : uint8_t {
    limit  = 0,  ///< Limit order: rests in the book until filled or cancelled.
    cancel = 1,  ///< Cancel a previously submitted simulated order.
};

/// @brief A simulated order submitted by a strategy.
///
/// This represents the strategy's *intent* to place or cancel an order.
/// The Engine routes it through the LatencyModel (delay) and FillModel
/// (fill probability) before it takes effect.
struct SimOrder {
    uint64_t    sim_order_id;  ///< Strategy-assigned local order ID.
    SymbolId    symbol;        ///< Target instrument.
    SimOrderType type;         ///< Limit or cancel.
    Side        side;          ///< Bid or ask (ignored for cancel).
    Price       price;         ///< Limit price (ignored for cancel).
    Quantity    qty;           ///< Quantity (ignored for cancel).
    Timestamp   submit_ts;     ///< Timestamp when the strategy submits this order.
};

/// @brief A fill notification sent back to the strategy.
///
/// Generated by the FillModel when a simulated order is (partially) filled.
struct Fill {
    uint64_t  sim_order_id;    ///< Which simulated order was filled.
    SymbolId  symbol;          ///< Instrument.
    Side      side;            ///< Bid or ask.
    Price     fill_price;      ///< Execution price.
    Quantity  fill_qty;        ///< Number of shares filled.
    Timestamp fill_ts;         ///< Timestamp of the fill.
};

// ============================================================
// OrderSubmitter — strategy's interface to submit orders
// ============================================================

/// @brief Collects simulated orders from a strategy during a callback.
///
/// Passed by reference to `on_book_update`. The strategy calls `submit()`
/// to enqueue orders; the Engine drains them after the callback returns.
class OrderSubmitter {
public:
    /// @brief Submit a simulated order.
    /// @param order The SimOrder to enqueue.
    void submit(SimOrder order) {
        pending_.push_back(std::move(order));
    }

    /// @brief Drain all pending orders (called by Engine).
    /// @return Vector of pending orders; internal buffer is cleared.
    std::vector<SimOrder> drain() {
        std::vector<SimOrder> out;
        std::swap(out, pending_);
        return out;
    }

    /// @brief Check if there are pending orders.
    [[nodiscard]] bool empty() const { return pending_.empty(); }

private:
    std::vector<SimOrder> pending_;  ///< Buffered orders from the strategy.
};

// ============================================================
// Strategy concept
// ============================================================

/// @brief Concept constraining types that can serve as trading strategies.
///
/// A valid Strategy must provide:
/// - `on_book_update(symbol, book, event, submitter)`: called after each
///   market data event is applied to the book. The strategy may inspect
///   the updated book and submit orders via the submitter.
/// - `on_fill(fill)`: called when a simulated order is filled.
///
/// Both functions receive data by const-ref (except submitter, which is
/// mutated by `submit()`).
template <typename S>
concept Strategy = requires(S s, SymbolId sym, const LOB& book,
                            const Event& event, OrderSubmitter& sub,
                            const Fill& fill) {
    { s.on_book_update(sym, book, event, sub) };
    { s.on_fill(fill) };
};

} // namespace lobe
